### ISSUE TITLE
Version 0.32.2 causes nuxt prepare to fail

### ISSUE THREAD

**Issue by just-maik** [Diizzayy/nuxt-graphql-client#455]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.2
- Nuxt Version:     3.9.1
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  yarn@1.22.21
- Builder:          -
- User Config:      devtools, telemetry, modules, tailwindcss, experimental, runtimeConfig, graphql-client, security, app
- Runtime Modules:  @vueuse/nuxt@10.7.1, @nuxtjs/device@3.1.1, nuxt-security@1.0.0-rc.4, nuxt-graphql-client@0.2.32, nuxt-typed-router@3.5.1, nuxt-icon@0.6.8, nuxt-simple-sitemap@4.4.1, @dargmuesli/nuxt-cookie-control@7.2.3, @nuxtjs/tailwindcss@6.10.4
- Build Modules:    -
------------------------------

### Describe the bug

Using 0.32.2 causes the following error when running nuxt prepare after upgrading from 0.32.1

### Expected behaviour

Should run as expected

### Logs

```shell
$ nuxt prepare 

 WARN  Please avoid recursive environment variables ( loop: PROMPT_COMMAND > PROMPT_COMMAND )                                                                            2:14:12 PM


[2:14:13 PM]  ERROR  Error while requiring module nuxt-graphql-client: Error: Cannot find module '/home/runner/work/nuxt-graphql-client/nuxt-graphql-client/node_modules/.pnpm/jiti@1.21.0/node_modules/jiti/lib/index.js'
Require stack:
- /app/node_modules/nuxt-graphql-client/dist/module.mjs


 ERROR  Cannot find module '/home/runner/work/nuxt-graphql-client/nuxt-graphql-client/node_modules/.pnpm/jiti@1.21.0/node_modules/jiti/lib/index.js'                     2:14:13 PM
Require stack:
- /app/node_modules/nuxt-graphql-client/dist/module.mjs

  Require stack:
  - node_modules/nuxt-graphql-client/dist/module.mjs
  at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
  at Function.resolve (node:internal/modules/cjs/helpers:125:19)
  at _resolve (node_modules/jiti/dist/jiti.js:1:251148)
  at jiti (node_modules/jiti/dist/jiti.js:1:253746)
  at node_modules/nuxt-graphql-client/dist/module.mjs:1:199
  at evalModule (node_modules/jiti/dist/jiti.js:1:256443)
  at jiti (node_modules/jiti/dist/jiti.js:1:254371)
  at requireModule (node_modules/@nuxt/kit/dist/index.mjs:2219:26)
  at loadNuxtModuleInstance (node_modules/@nuxt/kit/dist/index.mjs:2451:92)
  at async installModule (node_modules/@nuxt/kit/dist/index.mjs:2407:47) 



 ERROR  Cannot find module '/home/runner/work/nuxt-graphql-client/nuxt-graphql-client/node_modules/.pnpm/jiti@1.21.0/node_modules/jiti/lib/index.js'                     2:14:13 PM
Require stack:
- /app/node_modules/nuxt-graphql-client/dist/module.mjs
```

**Comment by urbgimtam** [comment]
Same here.

**Comment by just-maik** [comment]
Reproduction: https://stackblitz.com/edit/github-73pfjh?file=package.json

**Comment by Henvy-Mango** [comment]
Same here
